---

- name: "Create config directory"
  file:
    path: "{{ znc_config_path | dirname }}"
    state: "directory"
    owner: "{{ znc_owner }}"
    group: "{{ znc_group }}"
    mode: "0700"

- name: "Generate config"
  template:
    src: "znc.conf.j2"
    dest: "{{ znc_config_path }}"
    mode: '0600'
    owner: "{{ znc_owner }}"
    group: "{{ znc_group }}"

# vi:sw=2:tabstop=2
