---

- name: "Add service file"
  template:
    src: "znc.service.j2"
    dest: "/etc/systemd/system/znc.service"
  notify:
    - "enable znc service"
    - "restart znc service"

# vi:sw=2:tabstop=2
