---

- name: "reload systemd"
  systemd:
    daemon_reload: "yes"

- name: "enable znc service"
  systemd:
    name: "znc"
    enabled: "yes"

- name: "restart znc service"
  systemd:
    name: "znc"
    state: "restarted"
